[settings]
chunk_processor_type = "Checkerboard"
analytics_type = "ColorHistogram"
hardware_output_type = "DebugDriver"

[screen_reading_config]
deep_in = 330
deep_out = 145

[led_position_config]
gap = 200
vertical_offset = 108
horizontal_offset = 64
led_length = 67
vertical_led_amount = 7
horizontal_led_amount = 14

[screen_config]
frame_width_px = 0
frame_height_px = 0
frame_width_mm = 620
frame_height_mm = 610
