[settings]
chunk_processor_type = "Checkerboard"
analytics_type = "ColorHistogram"
filter_chain = []
hardware_output_type = "DebugDriver"

[color_histogram_config]
precision_level = 10

[flags]
pipewire_conversion = false
save_token = true

[daemon_settings]
log_level = "Error"

[checkerboard_config]
pixel_step = 1
row_stride = 1

[checkerboard_config.config]
width = 0
height = 0

[frame_connection_config]
start_from = "Left"
direction = "Clockwise"

[gamma_filter_config]
gamma = 2.009999990463257

[ema_filter_config]
alpha = 0.5099999904632568
amount = 0

[led_position_config]
gap = 1
vertical_offset = 1
horizontal_offset = 1
led_length = 1
vertical_led_amount = 1
horizontal_led_amount = 1

[screen_reading_config]
deep_in = 1
deep_out = 1

[screen_config]
frame_width_px = 0
frame_height_px = 0
frame_width_mm = 1
frame_height_mm = 0
