[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
ctrlc = "3.4"
serialport = "4.3.0"

algorithms = { path = "../algorithms" }
threads = { path = "../threads" }
ffi = { path = "../ffi" }

[[bin]]
name = "ambient-lighting"
path = "src/main.rs"
