[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
ui-gen = { path = "../infra/ui-gen" }
config-gen = { path = "../infra/config-gen" }
algorithms = { path = "../algorithms" }
threads = { path = "../threads" }
ffi = { path = "../ffi" }
hardware_output = { path = "../hardware_output" }
core = { path = "../core" }
common ={ path = "../common"}

tokio = { version = "1.0", features = ["full"] }
axum = "0.7"
serde_json = "1.0"

[[bin]]
name = "ambient-lighting-ui"
path = "src/main.rs"
